spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://localhost:3306/pagepots
    driver-class-name: com.mysql.jdbc.Driver
    username: liuyuancheng
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


