server:
  port: 8081

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/pagepots?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
  data:
    rest:
      base-path: /api
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

pagepots:
  server:
    datacenterid: 1
    machineid: 1


logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG


