server:
  port: 8081

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/startinst?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
  data:
    rest:
      base-path: /api

  redis:
    database: 0
    host: localhost
    port: 6379
    password:

  devtools:
    restart:
      enabled: true


startinst:
  server:
    dataCenterId: 1
    machineId: 1

logging:
  level:
    org.springframework:
      data: INFO
      security: INFO
    com.startinst.dao.mapper.WidgetMapper: DEBUG
    com.startinst.dao.mapper.ItemMapper: DEBUG
    com.startinst.dao.mapper.PageMapper: DEBUG


security:
  oauth2:
    client:
      clientId: 233668646673605
      clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me

mybatis:
  configuration:
    map-underscore-to-camel-case: true





