spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/pageagg
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true


